CC = mipsel-linux-gcc

CFLAGS = -O3 -mips32r2 -Wall -Werror -I. -DGCW0
LDFLAGS = -lSDL -lSDL_mixer
DEFINES += -DSOUND_ENABLED
DEFINES += -DSAVE
OUTPUT = possum

SOURCES = src/main.c WRAPPER/GCW.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm src/*.o
	rm ${OUTPUT}
