(function(l,T,ka,h){function I(a,b,c){return setTimeout(J(a,c),b)}function u(a,b,c){return Array.isArray(a)?(n(a,c[b],c),!0):!1}function n(a,b,c){var d;if(a)if(a.forEach)a.forEach(b,c);else if(a.length!==h)for(d=0;d<a.length;)b.call(c,a[d],d,a),d++;else for(d in a)a.hasOwnProperty(d)&&b.call(c,a[d],d,a)}function m(a,b,c){b=b.prototype;var d;d=a.prototype=Object.create(b);d.constructor=a;d._super=b;c&&p(d,c)}function J(a,b){return function(){return a.apply(b,arguments)}}function K(a,b){return"function"==
typeof a?a.apply(b?b[0]||h:h,b):a}function x(a,b,c){n(y(b),function(b){a.addEventListener(b,c,!1)})}function z(a,b,c){n(y(b),function(b){a.removeEventListener(b,c,!1)})}function U(a,b){for(;a;){if(a==b)return!0;a=a.parentNode}return!1}function y(a){return a.trim().split(/\s+/g)}function v(a,b,c){if(a.indexOf&&!c)return a.indexOf(b);for(var d=0;d<a.length;){if(c&&a[d][c]==b||!c&&a[d]===b)return d;d++}return-1}function A(a){return Array.prototype.slice.call(a,0)}function V(a,b,c){for(var d=[],e=[],
f=0;f<a.length;){var g=b?a[f][b]:a[f];0>v(e,g)&&d.push(a[f]);e[f]=g;f++}c&&(d=b?d.sort(function(a,c){return a[b]>c[b]}):d.sort());return d}function B(a,b){for(var c,d=b[0].toUpperCase()+b.slice(1),e=0;e<W.length;){c=(c=W[e])?c+d:b;if(c in a)return c;e++}return h}function X(a){a=a.ownerDocument||a;return a.defaultView||a.parentWindow||l}function k(a,b){var c=this;this.manager=a;this.callback=b;this.element=a.element;this.target=a.options.inputTarget;this.domHandler=function(b){K(a.options.enable,[a])&&
c.handler(b)};this.init()}function la(a){var b=a.options.inputClass;return new (b?b:ma?L:na?C:Y?M:D)(a,oa)}function oa(a,b,c){var d=c.pointers.length,e=c.changedPointers.length,f=b&1&&0===d-e;c.isFirst=!!f;c.isFinal=!!(b&12&&0===d-e);f&&(a.session={});c.eventType=b;d=a.session;b=c.pointers;if(!d.firstInput){e=[];for(f=0;f<c.pointers.length;)e[f]={clientX:w(c.pointers[f].clientX),clientY:w(c.pointers[f].clientY)},f++;e={timeStamp:N(),pointers:e,center:Z(e),deltaX:c.deltaX,deltaY:c.deltaY};d.firstInput=
e}d.firstMultiple=!1;e=d.firstInput;d=(d=d.firstMultiple)?d.center:e.center;b=c.center=Z(b);c.timeStamp=N();c.deltaTime=c.timeStamp-e.timeStamp;c.distance=aa(d,b);b=c.deltaX;d=c.deltaY;b=b===d?1:O(b)>=O(d)?0>b?2:4:0>d?8:16;c.offsetDirection=b;c.maxPointers=1;b=a.element;U(c.srcEvent.target,b)&&(b=c.srcEvent.target);c.target=b;a.emit("hammer.input",c);a.recognize(c);a.session.prevInput=c}function Z(a){var b=a.length;if(1===b)return{x:w(a[0].clientX),y:w(a[0].clientY)};for(var c=0,d=0,e=0;e<b;)c+=a[e].clientX,
d+=a[e].clientY,e++;return{x:w(c/b),y:w(d/b)}}function aa(a,b,c){c||(c=pa);var d=b[c[0]]-a[c[0]];a=b[c[1]]-a[c[1]];return Math.sqrt(d*d+a*a)}function D(){this.evEl=qa;this.evWin=ra;this.pressed=!1;k.apply(this,arguments)}function L(){this.evEl=ba;this.evWin=ca;k.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function da(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";this.started=!1;k.apply(this,arguments)}function C(){this.evTarget=sa;this.targetIds=
{};k.apply(this,arguments)}function ta(a,b){var c=A(a.touches),d=this.targetIds;if(b&3&&1===c.length)return d[c[0].identifier]=!0,[c,c];var e,f=A(a.changedTouches),g=[],h=this.target;e=c.filter(function(a){return U(a.target,h)});if(1===b)for(c=0;c<e.length;)d[e[c].identifier]=!0,c++;for(c=0;c<f.length;)d[f[c].identifier]&&g.push(f[c]),b&12&&delete d[f[c].identifier],c++;if(g.length)return[V(e.concat(g),"identifier",!0),g]}function M(){k.apply(this,arguments);var a=J(this.handler,this);this.touch=
new C(this.manager,a);this.mouse=new D(this.manager,a);this.primaryTouch=null;this.lastTouches=[]}function ea(a){a=a.changedPointers[0];if(a.identifier===this.primaryTouch){var b={x:a.clientX,y:a.clientY};this.lastTouches.push(b);var c=this.lastTouches;setTimeout(function(){var a=c.indexOf(b);-1<a&&c.splice(a,1)},2500)}}function P(a,b){this.manager=a;this.set(b)}function ua(a){if(-1<a.indexOf("none"))return"none";var b=-1<a.indexOf("pan-x"),c=-1<a.indexOf("pan-y");return b&&c?"none":b||c?b?"pan-x":
"pan-y":-1<a.indexOf("manipulation")?"manipulation":"auto"}function q(a){this.options=p({},this.defaults,a||{});this.id=va++;this.manager=null;a=this.options.enable;this.options.enable=a===h?!0:a;this.state=1;this.simultaneous={};this.requireFail=[]}function fa(a){return a&16?"cancel":a&8?"end":a&4?"move":a&2?"start":""}function ga(a){return 16==a?"down":8==a?"up":2==a?"left":4==a?"right":""}function E(a,b){var c=b.manager;return c?c.get(a):a}function t(){q.apply(this,arguments)}function F(){t.apply(this,
arguments);this.pY=this.pX=null}function Q(){q.apply(this,arguments);this._input=this._timer=null}function R(){t.apply(this,arguments)}function G(){q.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function r(a,b){b=b||{};var c=b.recognizers;b.recognizers=c===h?r.defaults.preset:c;return new S(a,b)}function S(a,b){this.options=p({},r.defaults,b||{});this.options.inputTarget=this.options.inputTarget||a;this.handlers={};this.session={};this.recognizers=[];
this.oldCssProps={};this.element=a;this.input=la(this);this.touchAction=new P(this,this.options.touchAction);ha(this,!0);n(this.options.recognizers,function(a){var b=this.add(new a[0](a[1]));a[2]&&b.recognizeWith(a[2]);a[3]&&b.requireFailure(a[3])},this)}function ha(a,b){var c=a.element;if(c.style){var d;n(a.options.cssProps,function(e,f){d=B(c.style,f);b?(a.oldCssProps[d]=c.style[d],c.style[d]=e):c.style[d]=a.oldCssProps[d]||""});b||(a.oldCssProps={})}}function wa(a,b){var c=T.createEvent("Event");
c.initEvent(a,!0,!0);c.gesture=b;b.target.dispatchEvent(c)}var W=" webkit Moz MS ms o".split(" "),xa=T.createElement("div"),w=Math.round,O=Math.abs,N=Date.now,p;p="function"!==typeof Object.assign?function(a){if(a===h||null===a)throw new TypeError("Cannot convert undefined or null to object");for(var b=Object(a),c=1;c<arguments.length;c++){var d=arguments[c];if(d!==h&&null!==d)for(var e in d)d.hasOwnProperty(e)&&(b[e]=d[e])}return b}:Object.assign;var va=1,ya=/mobile|tablet|ip(ad|hone|od)|android/i,
Y="ontouchstart"in l,ma=B(l,"PointerEvent")!==h,na=Y&&ya.test(navigator.userAgent),pa=["x","y"];k.prototype={handler:function(){},init:function(){this.evEl&&x(this.element,this.evEl,this.domHandler);this.evTarget&&x(this.target,this.evTarget,this.domHandler);this.evWin&&x(X(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&z(this.element,this.evEl,this.domHandler);this.evTarget&&z(this.target,this.evTarget,this.domHandler);this.evWin&&z(X(this.element),this.evWin,this.domHandler)}};
var za={mousedown:1,mousemove:2,mouseup:4},qa="mousedown",ra="mousemove mouseup";m(D,k,{handler:function(a){var b=za[a.type];b&1&&0===a.button&&(this.pressed=!0);b&2&&1!==a.which&&(b=4);this.pressed&&(b&4&&(this.pressed=!1),this.callback(this.manager,b,{pointers:[a],changedPointers:[a],pointerType:"mouse",srcEvent:a}))}});var Aa={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ba={2:"touch",3:"pen",4:"mouse",5:"kinect"},ba="pointerdown",ca="pointermove pointerup pointercancel";
l.MSPointerEvent&&!l.PointerEvent&&(ba="MSPointerDown",ca="MSPointerMove MSPointerUp MSPointerCancel");m(L,k,{handler:function(a){var b=this.store,c=!1,d=a.type.toLowerCase().replace("ms",""),d=Aa[d],e=Ba[a.pointerType]||a.pointerType,f="touch"==e,g=v(b,a.pointerId,"pointerId");d&1&&(0===a.button||f)?0>g&&(b.push(a),g=b.length-1):d&12&&(c=!0);0>g||(b[g]=a,this.callback(this.manager,d,{pointers:b,changedPointers:[a],pointerType:e,srcEvent:a}),c&&b.splice(g,1))}});var Ca={touchstart:1,touchmove:2,touchend:4,
touchcancel:8};m(da,k,{handler:function(a){var b=Ca[a.type];1===b&&(this.started=!0);if(this.started){var c;c=A(a.touches);var d=A(a.changedTouches);b&12&&(c=V(c.concat(d),"identifier",!0));c=[c,d];b&12&&0===c[0].length-c[1].length&&(this.started=!1);this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:a})}}});var Da={touchstart:1,touchmove:2,touchend:4,touchcancel:8},sa="touchstart touchmove touchend touchcancel";m(C,k,{handler:function(a){var b=Da[a.type],
c=ta.call(this,a,b);c&&this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:a})}});m(M,k,{handler:function(a,b,c){var d="touch"==c.pointerType,e="mouse"==c.pointerType;if(!(e&&c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents)){if(d)b&1?(this.primaryTouch=c.changedPointers[0].identifier,ea.call(this,c)):b&12&&ea.call(this,c);else{if(d=e)a:{for(var d=c.srcEvent.clientX,e=c.srcEvent.clientY,f=0;f<this.lastTouches.length;f++){var g=this.lastTouches[f],
h=Math.abs(e-g.y);if(25>=Math.abs(d-g.x)&&25>=h){d=!0;break a}}d=!1}if(d)return}this.callback(a,b,c)}},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var ia=B(xa.style,"touchAction"),ja=ia!==h,H=function(){if(!ja)return!1;var a={},b=l.CSS&&l.CSS.supports;"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(c){a[c]=b?l.CSS.supports("touch-action",c):!0});return a}();P.prototype={set:function(a){"compute"==a&&(a=this.compute());ja&&this.manager.element.style&&
H[a]&&(this.manager.element.style[ia]=a);this.actions=a.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var a=[];n(this.manager.recognizers,function(b){K(b.options.enable,[b])&&(a=a.concat(b.getTouchAction()))});return ua(a.join(" "))},preventDefaults:function(a){var b=a.srcEvent,c=a.offsetDirection;if(this.manager.session.prevented)b.preventDefault();else{var d=this.actions,e=-1<d.indexOf("none")&&!H.none,f=-1<d.indexOf("pan-y")&&!H["pan-y"],
d=-1<d.indexOf("pan-x")&&!H["pan-x"];if(e){var g=2>a.distance,h=250>a.deltaTime;if(1===a.pointers.length&&g&&h)return}if(!d||!f)if(e||f&&c&6||d&&c&24)return this.preventSrc(b)}},preventSrc:function(a){this.manager.session.prevented=!0;a.preventDefault()}};q.prototype={defaults:{},set:function(a){p(this.options,a);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(a){if(u(a,"recognizeWith",this))return this;var b=this.simultaneous;a=E(a,this);b[a.id]||(b[a.id]=a,a.recognizeWith(this));
return this},dropRecognizeWith:function(a){if(u(a,"dropRecognizeWith",this))return this;a=E(a,this);delete this.simultaneous[a.id];return this},requireFailure:function(a){if(u(a,"requireFailure",this))return this;var b=this.requireFail;a=E(a,this);-1===v(b,a)&&(b.push(a),a.requireFailure(this));return this},dropRequireFailure:function(a){if(u(a,"dropRequireFailure",this))return this;a=E(a,this);a=v(this.requireFail,a);-1<a&&this.requireFail.splice(a,1);return this},hasRequireFailures:function(){return 0<
this.requireFail.length},canRecognizeWith:function(a){return!!this.simultaneous[a.id]},emit:function(a){function b(b){c.manager.emit(b,a)}var c=this,d=this.state;8>d&&b(c.options.event+fa(d));b(c.options.event);a.additionalEvent&&b(a.additionalEvent);8<=d&&b(c.options.event+fa(d))},tryEmit:function(a){if(this.canEmit())return this.emit(a);this.state=32},canEmit:function(){for(var a=0;a<this.requireFail.length;){if(!(this.requireFail[a].state&33))return!1;a++}return!0},recognize:function(a){a=p({},
a);K(this.options.enable,[this,a])?(this.state&56&&(this.state=1),this.state=this.process(a),this.state&30&&this.tryEmit(a)):(this.reset(),this.state=32)},process:function(a){},getTouchAction:function(){},reset:function(){}};m(t,q,{defaults:{pointers:1},attrTest:function(a){var b=this.options.pointers;return 0===b||a.pointers.length===b},process:function(a){var b=this.state,c=a.eventType,d=b&6;a=this.attrTest(a);return d&&(c&8||!a)?b|16:d||a?c&4?b|8:b&2?b|4:2:32}});m(F,t,{defaults:{event:"pan",threshold:10,
pointers:1,direction:30},getTouchAction:function(){var a=this.options.direction,b=[];a&6&&b.push("pan-y");a&24&&b.push("pan-x");return b},directionTest:function(a){var b=this.options,c=!0,d=a.distance,e=a.direction,f=a.deltaX,g=a.deltaY;e&b.direction||(b.direction&6?(e=0===f?1:0>f?2:4,c=f!=this.pX,d=Math.abs(a.deltaX)):(e=0===g?1:0>g?8:16,c=g!=this.pY,d=Math.abs(a.deltaY)));a.direction=e;return c&&d>b.threshold&&e&b.direction},attrTest:function(a){return t.prototype.attrTest.call(this,a)&&(this.state&
2||!(this.state&2)&&this.directionTest(a))},emit:function(a){this.pX=a.deltaX;this.pY=a.deltaY;var b=ga(a.direction);b&&(a.additionalEvent=this.options.event+b);this._super.emit.call(this,a)}});m(Q,q,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},process:function(a){var b=this.options,c=a.pointers.length===b.pointers,d=a.distance<b.threshold,e=a.deltaTime>b.time;this._input=a;if(!d||!c||a.eventType&12&&!e)this.reset();else if(a.eventType&1)this.reset(),
this._timer=I(function(){this.state=8;this.tryEmit()},b.time,this);else if(a.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},emit:function(a){8===this.state&&(a&&a.eventType&4?this.manager.emit(this.options.event+"up",a):(this._input.timeStamp=N(),this.manager.emit(this.options.event,this._input)))}});m(R,t,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return F.prototype.getTouchAction.call(this)},attrTest:function(a){var b=
this.options.direction,c;b&30?c=a.overallVelocity:b&6?c=a.overallVelocityX:b&24&&(c=a.overallVelocityY);return this._super.attrTest.call(this,a)&&b&a.offsetDirection&&a.distance>this.options.threshold&&a.maxPointers==this.options.pointers&&O(c)>this.options.velocity&&a.eventType&4},emit:function(a){var b=ga(a.offsetDirection);b&&this.manager.emit(this.options.event+b,a);this.manager.emit(this.options.event,a)}});m(G,q,{defaults:{event:"tap",pointers:1,taps:1,interval:150,time:250,threshold:9,posThreshold:10},
getTouchAction:function(){return["manipulation"]},process:function(a){var b=this.options,c=a.pointers.length===b.pointers,d=a.distance<b.threshold,e=a.deltaTime<b.time;this.reset();if(a.eventType&1&&0===this.count)return this.failTimeout();if(d&&e&&c){if(4!=a.eventType)return this.failTimeout();c=this.pTime?a.timeStamp-this.pTime<b.interval:!0;d=!this.pCenter||aa(this.pCenter,a.center)<b.posThreshold;this.pTime=a.timeStamp;this.pCenter=a.center;this.count=d&&c?this.count+1:1;this._input=a;if(0===
this.count%b.taps)return this.hasRequireFailures()?(this._timer=I(function(){this.state=8;this.tryEmit()},b.interval,this),2):8}return 32},failTimeout:function(){this._timer=I(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});r.VERSION="2.0.8";r.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,
preset:[[R,{direction:6}],[F,{direction:6},["swipe"]],[G],[G,{event:"doubletap",taps:2},["tap"]],[Q]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};S.prototype={set:function(a){p(this.options,a);a.touchAction&&this.touchAction.update();a.inputTarget&&(this.input.destroy(),this.input.target=a.inputTarget,this.input.init());return this},stop:function(a){this.session.stopped=a?2:1},recognize:function(a){var b=
this.session;if(!b.stopped){this.touchAction.preventDefaults(a);var c,d=this.recognizers,e=b.curRecognizer;if(!e||e&&e.state&8)e=b.curRecognizer=null;for(var f=0;f<d.length;)c=d[f],2===b.stopped||e&&c!=e&&!c.canRecognizeWith(e)?c.reset():c.recognize(a),!e&&c.state&14&&(e=b.curRecognizer=c),f++}},get:function(a){if(a instanceof q)return a;for(var b=this.recognizers,c=0;c<b.length;c++)if(b[c].options.event==a)return b[c];return null},add:function(a){if(u(a,"add",this))return this;var b=this.get(a.options.event);
b&&this.remove(b);this.recognizers.push(a);a.manager=this;this.touchAction.update();return a},remove:function(a){if(u(a,"remove",this))return this;if(a=this.get(a)){var b=this.recognizers;a=v(b,a);-1!==a&&(b.splice(a,1),this.touchAction.update())}return this},on:function(a,b){if(a!==h&&b!==h){var c=this.handlers;n(y(a),function(a){c[a]=c[a]||[];c[a].push(b)});return this}},off:function(a,b){if(a!==h){var c=this.handlers;n(y(a),function(a){b?c[a]&&c[a].splice(v(c[a],b),1):delete c[a]});return this}},
emit:function(a,b){this.options.domEvents&&wa(a,b);var c=this.handlers[a]&&this.handlers[a].slice();if(c&&c.length){b.type=a;b.preventDefault=function(){b.srcEvent.preventDefault()};for(var d=0;d<c.length;)c[d](b),d++}},destroy:function(){this.element&&ha(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};p(r,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,
DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:S,Input:k,TouchAction:P,TouchInput:C,MouseInput:D,PointerEventInput:L,TouchMouseInput:M,SingleTouchInput:da,Recognizer:q,AttrRecognizer:t,Tap:G,Pan:F,Swipe:R,Press:Q,on:x,off:z,each:n,assign:p,inherit:m,bindFn:J,prefixed:B});("undefined"!==typeof l?l:"undefined"!==typeof self?self:{}).Hammer=r;"function"===typeof define&&define.amd?define(function(){return r}):
"undefined"!=typeof module&&module.exports?module.exports=r:l[ka]=r})(window,document,"Hammer"); 
